version: '3'
services:
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"  # Web UI for viewing sent emails
      - "1025:1025"  # SMTP port for your applications to send emails
